name: Nombre completo
description: Etiquetar imagen

inputs:
  nombre_imagen:
    required: true
  version:
    required: true

outputs:
  nombre_completo:
    value: ${{steps.nombre_completo.outputs.nombre_completo}}

runs:
  using: "composite"
  steps:

      
    - name: Guardar nombre completo 
      id: nombre_completo
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
           echo "nombre_completo=${{ inputs.nombre_imagen }}:${{ inputs.version }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.ref }}" == "refs/heads/development" ]; then
         echo "nombre_completo=${{ inputs.nombre_imagen }}:${{ inputs.version }}-snapshot" >> $GITHUB_OUTPUT
        else
          echo "Rama distinta a main / develop, entorno no configurado"
        fi
         
      shell: bash
